### ISSUE TITLE
processImportAPI to generate a new document

### ISSUE THREAD

**Issue by clark703** [plomino/Plomino#349]
Hello,

I'm trying to import a csv to generate a document with processImportAPI method. The following is my code in an PlominoAgent named as "agtAutoImportCSV ":
db = PlominoContext.getParentDatabase()
db.processImportAPI('formTest', ',', /resources/test_csv, file_encoding='utf-8')

And I get the following error:
RuntimeError: Script (Python) agent_agtAutoImportCSV has errors.
invalid syntax (Script (Python), line 7)
Context is <PlominoAgent> /mydb/agtAutoImportCSV

The csv file is added in Resources Folder as "text/csv" Content Type and works fine with CSV importation of Replication. I'd appreciate that you could give a simple sample code of processImportAPI method and also tell me how to code in a case the csv is located at a directory such as "/tmp".

Thank you in advance!

**Comment by AshRaghav** [comment]
Hi Eric,

Quick question regarding open_url. I am getting the following error (out of the blue) over the last week or so 

line 14, in agent_ag010ImportCSVs
AttributeError: 'NoneType' object has no attribute 'sendall'

csv_server = 'ftp://<<username>>:<<password>>@domain'
csv_path   = '/repository/CustomImport/'
import_file = csv_server + csv_path + 'import.csv'
Log('File URL opened')
final_import = open_url(import_file, asFile=True)
db.processImportAPI('frmImport', ',', final_import, file_encoding='utf-8')

It is the line with open_url which is line 14. All this was working without any issue until a week, so I am quite confused on what is going on here. The file path is correct and valid. 

Any guidance would be appreciated. Thanks

**Comment by ebrehault** [comment]
Hi,

If you have upgraded Plomino recently from a version prior to 1.19, you might have issues with open_url because it requires now to use safe domains (see https://plomino.readthedocs.io/en/latest/classes/#plominoutils about safe domain declaration).
But I doubt that because your error message refers to a sendall attribute which has nothing to do with Plomino.
So I think you have a cached version of your formula compiled somewhere, you should refresh and/or debug (by adding logs to see exactly what is going on).

**Comment by AshRaghav** [comment]
Thank you for your reply.

We have v1.19 and I noticed the piece of code (below) relating to safe domains yesterday and have been wondering ever since whether this was causing the issue. Although we have had this version for a considerably long time. 

`def open_url(url, asFile=False, data=None):
    """ retrieve content from url
    """
    safe_domains = []
    for safedomains_utils in component.getUtilitiesFor(IPlominoSafeDomains):
        safe_domains += safedomains_utils[1].domains
    is_safe = False
    for domain in safe_domains:
        if (url.startswith(domain)
            or url.split("//")[1].split("/")[0].split('@')[-1] == domain):
            is_safe = True
            break
    if is_safe:
        if data and not isinstance(data, basestring):
            data = urllib.urlencode(data)
        f=urllib.urlopen(url, data)
        if asFile:
            return f.fp
        else:
            return f.read()
    else:
        raise Unauthorized(url)
`
I am refreshing the DB as we speak and recomputing documents where needed. I am also hoping to restart all the clients to ensure that I can workout effectively. If it still doesn't resolve then I'll try adding logs inside the open_url function and let you know the outcome. Thanks again

**Comment by AshRaghav** [comment]
Eric - thanks for your reply. Had sorted this problem by recomputing the documents, refreshing the database and restarting all the clients. 

Quite weird though that even when I didn't touch any of these agents, this issue cropped up out of the blue.
