### ISSUE TITLE
Displaying submitted data on a page form

### ISSUE THREAD

**Issue by instification** [plomino/Plomino#640]
# User Problem
When a user submits to a page form, it is displayed using OpenForm to render the form with the request values that were submitted.

There is no option to display the values, in a similar manner to the way a document is displayed after it is created.

The particular use case here is trying to generate a pdf from the submitted values via plone.subrequest.

# Options
1. Create a new view (DisplayForm) that renders the form in display mode, using the request values.
2. Modify OpenForm view to check for special request var, display form using that form instead.
3. Add a new form mode (search, page etc) and display the form in read mode if set.
4. Create a new form with display fields, using the computed for display formula to get the values from the request (requires no code changes but is cumbersome, especially for large forms).

**Comment by instification** [comment]
I have tried option 1 and it works well. I can create a PR to implement it.

**Comment by ebrehault** [comment]
I am not super fan of this idea (as we can already easily render what we want directly in a computed for display field and hide the rest).
But as the implementation is very simple, I guess it will not harm.

**Comment by instification** [comment]
So how does a computed for display field get the value from the request? 

If I create a form with an input field, I can go to OpenForm and use name=value to set the values on the form.  If the field is display mode it ignores the request var and there is no document for it to get the value (as we are in page mode).

**Comment by ebrehault** [comment]
like this:
```python
field1 = context.REQUEST.get('field1')
```

**Comment by instification** [comment]
I see. I think it is much simpler to do it that way, so the additional display form is not needed as we can create another form that takes care of presentation.

Thanks for your help Eric!

**Comment by djay** [comment]
I think creating new calculated fields is a lot of work..imagine a form with 100 fields. 
We have the ability to render a form in read-only mode if we have a document.  I think its reasonable to have a way render the form from a request in read-only mode. Maybe if we use a form event to create a temporary document and set the form to edit mode via some kind of api?

**Comment by ebrehault** [comment]
I agree this PR could be interesting (as I said, it should not harm, and it might be useful in some use cases)

**Comment by djay** [comment]
I agree having a dedicated view for this usecase is probably too much.
I think using OpenForm is ok if we can use a formula or settings to create a temporaryDocument and switch it to editmode=False.
If you look at https://github.com/plomino/Plomino/blob/ae38345305fc722ad5508407952f4cbec9a7ee90/Products/CMFPlomino/PlominoForm.py#L1051

We are mostly there. If its a Page form then we already have a temporaryDocument created. Not sure why that fact is not documented. 
We call beforecreate at this point.
I'm not sure how to do it, but what would be good is if beforecreate could set its own temporaryDocument and also set editmode=False. The problem is that beforecreate only takes an error. The only place I can think of setting those things are special variables in the REQUEST. Any other ideas @ebrehault ?

**Comment by ebrehault** [comment]
Yes I guess request parameters are the way to do it

**Comment by djay** [comment]
Do you think there are security issues? Since request params can be set from the url as well?
If not I propose in the beforeCreate we allow

```
REQUEST['plominoDocument'] = getTemporaryDocument(
                    db,
                    context,
                    REQUEST)

REQUEST['editmode'] = False
```

**Comment by djay** [comment]
I think the other alternative is we can add an editmode setting on the form object. Perhaps only relevant in Page Form mode. Perhaps its a new mode? Display Form? 
Since the temporaryDocument is already created then this would be enough for our needs and more preferable. What we are really after is a way to create a visual report of the data, when combined the ability reuse fields between forms, would make it easy to display the submitted data back in a different layout.

**Comment by ebrehault** [comment]
I think the initial proposal Jon made was actually good.
We create a DisplayForm template, and we just access it by calling `the_fom_url/DisplayForm`.
The only missing part is the ability to redirect a regular page form to this URL after submission.
For that, we could use the `plominoredirecturl` principle (already used here: https://github.com/plomino/Plomino/blob/github-main/Products/CMFPlomino/PlominoDocument.py#L422): we test if the current form has a field named `plominoredirecturl`, if so we computed its value, and use it to set the `<form>` tag action attribute.

**Comment by instification** [comment]
Eric, if we submit to this new displayform what would happen if there are form errors? 
We can't issue a redirect after submission as we need the request var.

Could we add some logic that displays the form again if there are errors? I'm not sure how easy that would be to do.

An alternative is to look at having the DisplayForm mode on the form (as per Dylans comment above). That would allow us to extend OpenForm.pt to display the forms using here.displayDocument() if validation passes.

**Comment by ebrehault** [comment]
Ok but I am not sure it would solve the issue: how do you decide to switch to `here.displayDocument()` ? You also need to know if the validation is ok, so that's pretty much the same to change the form's `action`  attribute.
Here is how I see it:
- your form contains a computed field named `plominoredirecturl`, and its formula returns `"./DisplayForm"`,
- on the client side, we already have a `submit` event that makes a call to `./validation_errors`, we just need to include in its success message the value of the `plominoredirecturl` field in ordert o put it in the current form's `action` attribute.

But if you have another implementation in mind, no problem.

**Comment by djay** [comment]
Not 100% on the special field Id. Seems like its introducing an event or
formula by another unexpected means.
An alternative would be to continue to use the beforecreate event but it
can set the with_form request var to determine which final form is used.
Another idea is to do this as part of an action submit formula?

**Comment by instification** [comment]
Issue resolved by https://github.com/plomino/Plomino/pull/642
