### ISSUE TITLE
Datagrid has js error when starting empty

### ISSUE THREAD

**Issue by djay** [plomino/Plomino#652]
```Uncaught TypeError: Cannot read property 'length' of undefined```
Table appears as just "...loading".

Shouldn't the table appear with at least one row?

**Comment by ebrehault** [comment]
I think this error is not due to the number of rows, but to the number of columns.
Have a look to the field mapping.

**Comment by instification** [comment]
I think the issue is related to the way tojson is called on a PlominoForm (as opposed to PlominoDocument). If a document has an empty field, a blank array is returned, whereas when it is a form, an empty string `''` is returned.

I did some work to try and fix it https://github.com/instification/Plomino/commit/02a7f18f8b022e9265615f177aea1a1507ba4cac but it failed the jenkins test. I cannot get it to replicate locally (I created issue #655 for this).
