### ISSUE TITLE
problems setting up testing

### ISSUE THREAD

**Issue by instification** [plomino/Plomino#655]
I am trying to run tests locally, using the following buildout:

```
[buildout]
extends = https://raw.github.com/collective/buildout.plonetest/master/test-4.x.cfg
package-name = Products.CMFPlomino
package-extras = [test]
```

Most of the tests pass, but there are 3 failures. 2 are connection refused and the other a teardown error.

Full output is here: http://pastebin.com/RCxHuUJR

It appears to be trying to connect to a remote server, although the server doesn't get started. By running plone on that port, the tests then pass.

**Comment by ebrehault** [comment]
Right, that's because we haven't found a way to test the replication and the design import over HTTP just using the Plone testing instance (it cannot handle subrequest).
So our tests expect to have a local instance running on localhost:8080.

By the way, if you want a proper test setup, just have a look to https://github.com/plomino/Plomino/blob/github-main/.travis.yml
