### ISSUE TITLE
DbTraverse on a view column

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#814]
Hi all.
I have 2 Plomino database (_Cash 2016_ and _Cash 2017_) with the same fields (more or less).
I wolud like to show in the "2017 view" values from _Cash 2016_ db in a column in order to show differences (for example "total2016" from _Cash 2016_ db and _total2017_ from the current db
Is it possible to show in a view column a value from another Plomino database?

Thanks

Luca

**Comment by ebrehault** [comment]
It can work if the external db data do not change, because Plomino only guarantee views are updated when local documents are changed but not when external docs are changed.
The recommended approach is to create a Page form containing a computed for display datagrid (in that case we do not use any index, so it might be slower but it will be always up-to-date).

**Comment by ermancio** [comment]
Your advice is to create a Page form containing a computed for display datagrid.
But in my scenario (Cash2016 and Cash2017), where should I have to create the Page Form? And which form is that associated to the datagrid?

**Comment by ebrehault** [comment]
You do not need an associated form here, as you will just use the datagrid in read mode.
The idea is to use a datagrid to imitate a view, the difference being your datagrid field formula will produce the grid content at every display (and not just by calling an already generated index like view columns do)

**Comment by ermancio** [comment]
Ok. Thank you
