### ISSUE TITLE
Plomino fields to Plone event

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#818]
Hi all.
I would like to show information from a plomino document directly in a Plone event;
when I save a plomino document, I need to create a public event in Plone containing description (from a Plomino text field and date (same start/end date form a Plomino date field).

So:
- description (from Plomino to event title)
- date (from Plomino to event start date = event end date)

According to you is it possible?
Luca

**Comment by ebrehault** [comment]
Yes, it is possible.
There are 2 approaches:

- in the form onSave, create or update an event and set the appropriate values
- just check "Index document in portal" in your db settinsg, and let Plomino documents to behave like events (you just need to make sure they have the startDate and endDate Plone expects)

**Comment by ermancio** [comment]
Hi Eric,
could you send me an example for both approaches (expecially for first one)?
For the second one, how do I set the behaviour of Plomino documents?

Thanks

**Comment by ebrehault** [comment]
Actually, first one is not possible with pure Plomino because of security restrictions.
You could do it with Rapido, or you would need to create a browserview or an external method able to use the Plone API to create new events.

Regarding the second approach, when I said "behave", I didn't mean Dexterity behavior. Any object having a 'start' property and a 'end' property can be displayed in a calendar. So just create 2 date fields in your Plomino form (start and end), index the docs in the portal, and then create a collection or whatever you want, they will just be like events.

**Comment by ermancio** [comment]
Ok.
Thank you very much

**Comment by ermancio** [comment]
I tried to set two fields (startDate, endDate) but no results in my collection when I filter for event start date or event end date.
The collection results my Plomino documents but filtering for event dates does not work,...

**Comment by ebrehault** [comment]
that's start and end (not startDate and endDate)

**Comment by ermancio** [comment]
Unless it depends on the fact that the dates must coincide (startDate and endDate are 2017/06/15 00:00:00 GMT+2)

**Comment by ermancio** [comment]
so my fields must be named start/end?

**Comment by ebrehault** [comment]
yes

**Comment by ermancio** [comment]
It works!
Thank you Eric.
